dual_controller:
    type: dual_controllers/DualController
    left:
        arm_id: panda_left
        joint_names:
            - left_panda_joint1
            - left_panda_joint2
            - left_panda_joint3
            - left_panda_joint4
            - left_panda_joint5
            - left_panda_joint6
            - left_panda_joint7
    right:
        arm_id: panda_right
        joint_names:
            - right_panda_joint1
            - right_panda_joint2
            - right_panda_joint3
            - right_panda_joint4
            - right_panda_joint5
            - right_panda_joint6
            - right_panda_joint7
